### ISSUE TITLE
Improve diagnostic output for certain operaitons

### ISSUE THREAD

**Issue by ayurchen** [codership/wsrep-lib#127]
Some methods in wsrep-lib still hide/ignore return codes from provider which complicates diagnostics and debugging, e.g.
```
2020-03-26 15:48:15 0 [ERROR] WSREP: Failed to create a new provider '/home/elenst/galera/galera-4.so' with options '':Failed to set encryption key
```
Here we have a very generic error statement which gives little insight into the issue: was there something wrong with the key?, was the function not implemented?, etc.

Improve error logging for
`sst_sent()`
`sst_received()`
`set_encryption_key()`

**Comment by sciascid** [comment]
Fixed in commit daae4a9c353aa80ddc29e37eb041c50c6bcf2c47
