### ISSUE TITLE
client_state.cpp:121: int wsrep::client_state::before_command(): Assertion `server_state_.rollback_mode() == wsrep::server_state::rm_async' failed.

### ISSUE THREAD

**Issue by temeo** [codership/wsrep-lib#135]
An assertion
```
client_state.cpp:121: int wsrep::client_state::before_command(): Assertion `server_state_.rollback_mode() == wsrep::server_state::rm_async' failed.
```
occurs if the client session acquires ownership via
```
wait_rollback_complete_and_acquire_ownership()
```
before BF abort happens. Because client session has now ownership, the control is not given for rollbacker and it is up to client session to terminate the transaction. Therefore the state must remain in `s_must_abort` and the client session hits wrong assertion in `before_command()`.

**Comment by sciascid** [comment]
A fix has been pushed in 3e5a28df32c85c7768dd84d1731ad4661bf90022. Closing.
